### PR TITLE
strip trailing == from base64 content

### PR DESCRIPTION
**Pull request by mmerickel**
This is how the `SignedSerializer` and `SignedCookieSessionFactory` work in pyramid, so I wanted to try and keep it consistent. Dropping a couple bytes from a cookie isn't a bad thing!

### CODE REVIEW

**Comment by tseaver** [comment]
Py3k test failures.

**Comment by mmerickel** [comment]
Fixed that and along the way discovered that there was no test ensuring that the library actually worked. `SecretBox` was being mocked out everywhere... so anyway, the tests now ensure things should actually work.

**Comment by tseaver** [comment]
Still failing for coverage.

**Comment by mmerickel** [comment]
Yep... fixed that and added another fix for not converting a `CryptoError` into a `ValueError` as required by the `BaseCookieSessionFactory.loads` contract.

**Pull request merged**
