### PR TITLE
add EncryptedCookieSessionFactory

### PR DESCRIPTION
**Pull request by mmerickel**

### CODE REVIEW

**Comment by mmerickel** [comment]
Any suggestions to improve the testing procedure here without repeating 50-odd tests that are already done in pyramid for the `BaseCookieSessionFactory`? I added a simple test just to ensure it's tracking the content across requests.

**Comment by mmerickel** [comment]
@tseaver any word on why this and #7 haven't been merged? I'd do it myself but I still need you to push to pypi unless you want to grant me access there.

**Comment by tseaver** [comment]
I'm fine with both PRs:  0.2 was all I needed, so I lost focus.

Feel free to fix the conflicts and merge, and ping me for a release to PyPI.

**Comment by mmerickel** [comment]
@tseaver 0.3 should be ready

**Comment by tseaver** [comment]
[Released](https://pypi.python.org/pypi/pyramid_nacl_session/0.3)

**Comment by mmerickel** [comment]
Thanks @tseaver !

**Pull request merged**
